image: condaforge/mambaforge

pages:
  script:
    - conda env create -f analysis/environment.yml
    - source activate ponio-analysis-env
    - mkdir public
    - python analysis/analysis.py -i database/butcher_tableaus.json -o public/api
    - cp html/*.html html/*.css html/*.js html/*.ico public
  artifacts:
    paths:
      - public
  only:
    - main

